[capture]
target = "camera"

[video]
path = ""

[image]
path = ""

[camera]
camera_choose = "dahua"
exposure_time = 4000.0
gain = 1.0
white_balance_blue = 1.7
white_balance_green = 1.0
white_balance_red = 1.6

[arm_detect]
color = true
thread_img = 125

[model]
model_path = "/home/shunxiaochuan/RM_VISION_2023_IST/RM_VISION_2023_IST/src/arms_detector/model/fc.onnx"
label_path = "/home/shunxiaochuan/RM_VISION_2023_IST/RM_VISION_2023_IST/src/arms_detector/model/label.txt"
thread_confence = 90.0
